# settings.yml
project: relay
name: RelayController
version: 0.0.1
settings:
  - name: HttpUrl
    type: std::string
    default: https://192.168.1.50/mini_games/lights/lights.json
    key: h_url
  - name: HttpDelay
    type: int
    default: 300
    key: h_delay
    min: 0
    max: 10000
  - name: MqttId
    type: int
    default: 0
    key: l_mqtt_id
    min: 0
    max: 4096
  - name: Ip
    type: std::string
    default: 192.168.0.111
    key: mq_ip
  - name: Port
    type: int
    default: 8081
    key: mq_port
    min: 0
    max: 65535